author:
  name: Christian Joudrey
  gravatar: '85b03650a2ec5235376b0b983a49511a'
  github: 'https://github.com/cjoudrey'
  twitter: 'https://twitter.com/cjoudrey'
markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
regeneration: true
